//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_KDCLPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetails
    {
        public int idorder { get; set; }
        public int idproduct { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
