// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC1DangKyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC1DangKy() {
    driver.Navigate().GoToUrl("https://www.demoblaze.com/index.html");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.Close();
    driver.Close();
    driver.FindElement(By.Id("signin2")).Click();
    driver.FindElement(By.Id("sign-username")).Click();
    driver.FindElement(By.Id("sign-username")).SendKeys("haha231");
    driver.FindElement(By.Id("sign-password")).Click();
    driver.FindElement(By.Id("sign-password")).SendKeys("123456789");
    driver.FindElement(By.CssSelector("#signInModal .btn-primary")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("This user already exist."));
    driver.FindElement(By.Id("sign-username")).Click();
    driver.FindElement(By.Id("sign-username")).SendKeys("son123456");
    driver.FindElement(By.Id("sign-password")).SendKeys("123456");
    driver.FindElement(By.CssSelector("#signInModal .btn-primary")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Sign up successful."));
  }
}
