// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC3HomeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC3Home() {
    driver.Navigate().GoToUrl("https://www.demoblaze.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector(".active > .nav-link")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .card-img-top")).Click();
    driver.FindElement(By.Id("nava")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(5) .card-img-top")).Click();
    driver.FindElement(By.CssSelector("#nava > img")).Click();
    driver.FindElement(By.Id("next2")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .card-img-top")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .card-img-top")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(2) .card-img-top")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(6) .card-img-top")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .card-img-top")).Click();
    driver.FindElement(By.Id("itemc")).Click();
    driver.FindElement(By.LinkText("Laptops")).Click();
    driver.FindElement(By.CssSelector(".col-lg-4:nth-child(3) .card-img-top")).Click();
    driver.FindElement(By.LinkText("Add to cart")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Product added."));
    driver.FindElement(By.Id("nava")).Click();
    driver.FindElement(By.CssSelector(".col-sm-4:nth-child(1) .caption")).Click();
    driver.FindElement(By.CssSelector(".col-sm-4 p")).Click();
    driver.FindElement(By.Id("next2")).Click();
    driver.FindElement(By.LinkText("Apple monitor 24")).Click();
    driver.FindElement(By.LinkText("Add to cart")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Product added."));
    driver.FindElement(By.CssSelector(".active > .nav-link")).Click();
    driver.FindElement(By.LinkText("Monitors")).Click();
    driver.FindElement(By.LinkText("Laptops")).Click();
    driver.FindElement(By.Id("itemc")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-prev-icon")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-prev-icon")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-prev-icon")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-next-icon")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-next-icon")).Click();
    driver.FindElement(By.CssSelector(".carousel-control-next-icon")).Click();
  }
}
